# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS   := xdpsock
BPF_TARGETS    := xdpsock_kern
EXTRA_DEPS := helpers.h

LDLIBS += -lpthread
LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
